spring.application.name=bookstore-api

# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs

# Specify the OpenAPI version to use (e.g., OPENAPI_3_0 or OPENAPI_3_1)
springdoc.api-docs.version=OPENAPI_3_1

# Disable the Swagger UI, we only want the OpenAPI
springdoc.swagger-ui.enabled=false
