/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CoffeeTypes } from "./coffeetypes.js";
import { Orders } from "./orders.js";

export class SpeakeasyCoffeeClient extends ClientSDK {
  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _coffeeTypes?: CoffeeTypes;
  get coffeeTypes(): CoffeeTypes {
    return (this._coffeeTypes ??= new CoffeeTypes(this._options));
  }
}
