// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetOrders(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "GetOrders-multiple_orders[0]":
			dir.HandlerFunc("GetOrders", testGetOrdersGetOrdersMultipleOrders0)(w, req)
		case "GetOrders-latte[0]":
			dir.HandlerFunc("GetOrders", testGetOrdersGetOrdersLatte0)(w, req)
		case "GetOrders-espresso[0]":
			dir.HandlerFunc("GetOrders", testGetOrdersGetOrdersEspresso0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetOrdersGetOrdersMultipleOrders0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-API-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := []components.CoffeeOrder{
		components.CoffeeOrder{
			ID:           1,
			CustomerName: "Alice",
			CoffeeType:   "Latte",
			Size:         components.CoffeeOrderSizeMedium,
			Extras: []string{
				"Extra shot",
				"Soy milk",
			},
			Price: 4.5,
		},
		components.CoffeeOrder{
			ID:           2,
			CustomerName: "Bob",
			CoffeeType:   "Espresso",
			Size:         components.CoffeeOrderSizeSmall,
			Extras: []string{
				"Extra shot",
			},
			Price: 3.5,
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testGetOrdersGetOrdersLatte0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-API-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := []components.CoffeeOrder{
		components.CoffeeOrder{
			ID:           5,
			CustomerName: "Eve",
			CoffeeType:   "Mocha",
			Size:         components.CoffeeOrderSizeLarge,
			Extras: []string{
				"Whipped cream",
				"Chocolate syrup",
			},
			Price: 6,
		},
		components.CoffeeOrder{
			ID:           6,
			CustomerName: "Grace",
			CoffeeType:   "Cold Brew",
			Size:         components.CoffeeOrderSizeMedium,
			Extras: []string{
				"Vanilla syrup",
			},
			Price: 5.5,
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testGetOrdersGetOrdersEspresso0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityHeader(req, "X-API-Key", false); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := []components.CoffeeOrder{
		components.CoffeeOrder{
			ID:           5,
			CustomerName: "Eve",
			CoffeeType:   "Mocha",
			Size:         components.CoffeeOrderSizeLarge,
			Extras: []string{
				"Whipped cream",
				"Chocolate syrup",
			},
			Price: 6,
		},
		components.CoffeeOrder{
			ID:           6,
			CustomerName: "Grace",
			CoffeeType:   "Cold Brew",
			Size:         components.CoffeeOrderSizeMedium,
			Extras: []string{
				"Vanilla syrup",
			},
			Price: 5.5,
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
