/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createTodo } from "../../funcs/createTodo.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.TodoForm$inboundSchema.optional(),
};

export const tool$createTodo: ToolDefinition<typeof args> = {
  name: "create-todo",
  description: `Create a todo item`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await createTodo(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
