/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { API } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("System Healthcheck", async () => {
  const testHttpClient = createTestHTTPClient("healthcheck");

  const API = new API({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["API_API_KEY"] ?? "value",
  });

  const result = await API.system.getHealthcheck();
  expect(result).toBeDefined();
});

test("System Heartbeat", async () => {
  const testHttpClient = createTestHTTPClient("heartbeat");

  const API = new API({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["API_API_KEY"] ?? "value",
  });

  const result = await API.system.getHeartbeat();
  expect(result).toBeDefined();
});

test("System Pre Flight Checks", async () => {
  const testHttpClient = createTestHTTPClient("pre_flight_checks");

  const API = new API({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["API_API_KEY"] ?? "value",
  });

  const result = await API.system.getPreFlightChecks();
  expect(result).toBeDefined();
});
