/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { API } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Tenants Create Tenant", async () => {
  const testHttpClient = createTestHTTPClient("create_tenant");

  const API = new API({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["API_API_KEY"] ?? "value",
  });

  const result = await API.tenants.create({
    name: "<value>",
  });
  expect(result).toBeDefined();
});

test("Tenants Get Tenant", async () => {
  const testHttpClient = createTestHTTPClient("get_tenant");

  const API = new API({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: process.env["API_API_KEY"] ?? "value",
  });

  const result = await API.tenants.get({
    tenantName: "<value>",
  });
  expect(result).toBeDefined();
});
