// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CoffeeType - Represents a type of coffee available in the system
type CoffeeType struct {
	// Name of the coffee type
	Name string `json:"name"`
	// Detailed description of the coffee type
	Description *string `json:"description,omitempty"`
	// Unique identifier for the coffee type
	ID int64 `json:"id"`
	// Price multiplier for this coffee type
	PriceMultiplier *float64 `json:"price_multiplier,omitempty"`
}

func (o *CoffeeType) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CoffeeType) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CoffeeType) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *CoffeeType) GetPriceMultiplier() *float64 {
	if o == nil {
		return nil
	}
	return o.PriceMultiplier
}
