/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * A booking for a train trip.
 */
export type CreateBookingXMLResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: models.LinksSelf | undefined;
};

/**
 * A booking for a train trip.
 */
export type CreateBookingResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: models.LinksSelf | undefined;
};

export type CreateBookingResponseResult =
  | CreateBookingResponseBody
  | Uint8Array
  | string;

export type CreateBookingResponse = {
  headers: { [k: string]: Array<string> };
  result: CreateBookingResponseBody | Uint8Array | string;
};

/** @internal */
export const CreateBookingXMLResponseBody$inboundSchema: z.ZodMiniType<
  CreateBookingXMLResponseBody,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    trip_id: types.optional(types.string()),
    passenger_name: types.optional(types.string()),
    has_bicycle: types.optional(types.boolean()),
    has_dog: types.optional(types.boolean()),
    links: types.optional(models.LinksSelf$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trip_id": "tripId",
      "passenger_name": "passengerName",
      "has_bicycle": "hasBicycle",
      "has_dog": "hasDog",
    });
  }),
);

export function createBookingXMLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingXMLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingXMLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingXMLResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingResponseBody$inboundSchema: z.ZodMiniType<
  CreateBookingResponseBody,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    trip_id: types.optional(types.string()),
    passenger_name: types.optional(types.string()),
    has_bicycle: types.optional(types.boolean()),
    has_dog: types.optional(types.boolean()),
    links: types.optional(models.LinksSelf$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trip_id": "tripId",
      "passenger_name": "passengerName",
      "has_bicycle": "hasBicycle",
      "has_dog": "hasDog",
    });
  }),
);

export function createBookingResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingResponseResult$inboundSchema: z.ZodMiniType<
  CreateBookingResponseResult,
  unknown
> = smartUnion([
  z.lazy(() => CreateBookingResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function createBookingResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateBookingResponse$inboundSchema: z.ZodMiniType<
  CreateBookingResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: smartUnion([
      z.lazy(() => CreateBookingResponseBody$inboundSchema),
      b64$.zodInbound,
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function createBookingResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingResponse' from JSON`,
  );
}
