/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { CoffeeExampleApiSDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$createCoffeeTypeCoffeeTypesPost } from "./tools/createCoffeeTypeCoffeeTypesPost.js";
import { tool$createOrderOrdersPost } from "./tools/createOrderOrdersPost.js";
import { tool$deleteCoffeeTypeCoffeeTypesTypeIdDelete } from "./tools/deleteCoffeeTypeCoffeeTypesTypeIdDelete.js";
import { tool$deleteOrderOrdersOrderIdDelete } from "./tools/deleteOrderOrdersOrderIdDelete.js";
import { tool$getCoffeeTypeCoffeeTypesTypeIdGet } from "./tools/getCoffeeTypeCoffeeTypesTypeIdGet.js";
import { tool$getCoffeeTypesCoffeeTypesGet } from "./tools/getCoffeeTypesCoffeeTypesGet.js";
import { tool$getOrderOrdersOrderIdGet } from "./tools/getOrderOrdersOrderIdGet.js";
import { tool$getOrdersOrdersGet } from "./tools/getOrdersOrdersGet.js";
import { tool$updateCoffeeTypeCoffeeTypesTypeIdPut } from "./tools/updateCoffeeTypeCoffeeTypesTypeIdPut.js";
import { tool$updateOrderOrdersOrderIdPut } from "./tools/updateOrderOrdersOrderIdPut.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "CoffeeExampleApiSDK",
    version: "0.10.4",
  });

  const client = new CoffeeExampleApiSDKCore({
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });
  const scopes = new Set(deps.scopes ?? mcpScopes);
  const tool = createRegisterTool(deps.logger, server, client, scopes);

  tool(tool$getOrdersOrdersGet);
  tool(tool$createOrderOrdersPost);
  tool(tool$getOrderOrdersOrderIdGet);
  tool(tool$updateOrderOrdersOrderIdPut);
  tool(tool$deleteOrderOrdersOrderIdDelete);
  tool(tool$getCoffeeTypesCoffeeTypesGet);
  tool(tool$createCoffeeTypeCoffeeTypesPost);
  tool(tool$getCoffeeTypeCoffeeTypesTypeIdGet);
  tool(tool$updateCoffeeTypeCoffeeTypesTypeIdPut);
  tool(tool$deleteCoffeeTypeCoffeeTypesTypeIdDelete);

  return server;
}
