openapi: 3.0.0
info:
  title: Todo API
  description: A minimal TODO API
  version: 1.0.0
servers:
  - url: https://todo.example.com
    description: Main API server
paths:
  /todo/{id}:
    get:
      description: Get a todo item by id
      operationId: getTodoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
  /todo:
    post:
      description: Create a todo item
      operationId: createTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoForm"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"

components:
  schemas:
    TodoForm:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Buy groceries"
        due_date:
          type: string
          format: date
          example: "2021-01-01"
        completed:
          type: boolean
          example: false

    Todo:
      type: object
      required:
        - id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          example: "123"
        title:
          type: string
          example: "Buy groceries"
        due_date:
          type: string
          format: date
          example: "2021-01-01"
        completed:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
