/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicationsGetPublication } from "../../funcs/publicationsGetPublication.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPublicationRequest$inboundSchema,
};

export const tool$publicationsGetPublication: ToolDefinition<typeof args> = {
  name: "publications-get-publication",
  description: `Get a publication by ID

Retrieves a publication's details by its unique identifier`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await publicationsGetPublication(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
