/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the openapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthGetHealth.example.ts
 */

import { SDK } from "openapi";

const sdk = new SDK({
  oAuth2: "<YOUR_O_AUTH2_HERE>",
});

async function main() {
  const result = await sdk.health.getHealth();

  console.log(result);
}

main().catch(console.error);
