/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTripsRequest = {
  origin: string;
  destination: string;
  date: string;
  page?: number | undefined;
  limit?: number | undefined;
  bicycles?: boolean | undefined;
  dogs?: boolean | undefined;
};

/** @internal */
export const GetTripsRequest$inboundSchema: z.ZodType<
  GetTripsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  origin: z.string(),
  destination: z.string(),
  date: z.string(),
  page: z.number().optional(),
  limit: z.number().optional(),
  bicycles: z.boolean().optional(),
  dogs: z.boolean().optional(),
});

/** @internal */
export type GetTripsRequest$Outbound = {
  origin: string;
  destination: string;
  date: string;
  page?: number | undefined;
  limit?: number | undefined;
  bicycles?: boolean | undefined;
  dogs?: boolean | undefined;
};

/** @internal */
export const GetTripsRequest$outboundSchema: z.ZodType<
  GetTripsRequest$Outbound,
  z.ZodTypeDef,
  GetTripsRequest
> = z.object({
  origin: z.string(),
  destination: z.string(),
  date: z.string(),
  page: z.number().optional(),
  limit: z.number().optional(),
  bicycles: z.boolean().optional(),
  dogs: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTripsRequest$ {
  /** @deprecated use `GetTripsRequest$inboundSchema` instead. */
  export const inboundSchema = GetTripsRequest$inboundSchema;
  /** @deprecated use `GetTripsRequest$outboundSchema` instead. */
  export const outboundSchema = GetTripsRequest$outboundSchema;
  /** @deprecated use `GetTripsRequest$Outbound` instead. */
  export type Outbound = GetTripsRequest$Outbound;
}

export function getTripsRequestToJSON(
  getTripsRequest: GetTripsRequest,
): string {
  return JSON.stringify(GetTripsRequest$outboundSchema.parse(getTripsRequest));
}

export function getTripsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsRequest' from JSON`,
  );
}
