// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AddCollectionRecordsPayload struct {
	Documents  []*string            `json:"documents,omitempty"`
	Embeddings [][]float32          `json:"embeddings,omitempty"`
	Ids        []string             `json:"ids"`
	Metadatas  []map[string]HashMap `json:"metadatas,omitempty"`
	Uris       []*string            `json:"uris,omitempty"`
}

func (o *AddCollectionRecordsPayload) GetDocuments() []*string {
	if o == nil {
		return nil
	}
	return o.Documents
}

func (o *AddCollectionRecordsPayload) GetEmbeddings() [][]float32 {
	if o == nil {
		return nil
	}
	return o.Embeddings
}

func (o *AddCollectionRecordsPayload) GetIds() []string {
	if o == nil {
		return []string{}
	}
	return o.Ids
}

func (o *AddCollectionRecordsPayload) GetMetadatas() []map[string]HashMap {
	if o == nil {
		return nil
	}
	return o.Metadatas
}

func (o *AddCollectionRecordsPayload) GetUris() []*string {
	if o == nil {
		return nil
	}
	return o.Uris
}
