// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChecklistResponse struct {
	MaxBatchSize int `json:"max_batch_size"`
}

func (o *ChecklistResponse) GetMaxBatchSize() int {
	if o == nil {
		return 0
	}
	return o.MaxBatchSize
}
