// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateTenantPayload struct {
	Name string `json:"name"`
}

func (o *CreateTenantPayload) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
