/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { shortURLsCreate } from "../../funcs/shortURLsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateRequest$inboundSchema,
};

export const tool$shortURLsCreate: ToolDefinition<typeof args> = {
  name: "short-UR-ls_create",
  description: `Shorten a URL.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await shortURLsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
