/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBookingsEmpty = {};

export type GetBookingsRequest = {
  empty?: GetBookingsEmpty | undefined;
};

export type GetBookingsResponse =
  | Array<models.SpeakeasyBooking>
  | models.RpcStatus;

/** @internal */
export type GetBookingsEmpty$Outbound = {};

/** @internal */
export const GetBookingsEmpty$outboundSchema: z.ZodMiniType<
  GetBookingsEmpty$Outbound,
  GetBookingsEmpty
> = z.object({});

export function getBookingsEmptyToJSON(
  getBookingsEmpty: GetBookingsEmpty,
): string {
  return JSON.stringify(
    GetBookingsEmpty$outboundSchema.parse(getBookingsEmpty),
  );
}

/** @internal */
export type GetBookingsRequest$Outbound = {
  empty?: GetBookingsEmpty$Outbound | undefined;
};

/** @internal */
export const GetBookingsRequest$outboundSchema: z.ZodMiniType<
  GetBookingsRequest$Outbound,
  GetBookingsRequest
> = z.object({
  empty: z.optional(z.lazy(() => GetBookingsEmpty$outboundSchema)),
});

export function getBookingsRequestToJSON(
  getBookingsRequest: GetBookingsRequest,
): string {
  return JSON.stringify(
    GetBookingsRequest$outboundSchema.parse(getBookingsRequest),
  );
}

/** @internal */
export const GetBookingsResponse$inboundSchema: z.ZodMiniType<
  GetBookingsResponse,
  unknown
> = smartUnion([
  z.array(models.SpeakeasyBooking$inboundSchema),
  models.RpcStatus$inboundSchema,
]);

export function getBookingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsResponse' from JSON`,
  );
}
