/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SDKError } from "./sdkerror.js";

/**
 * Not Found
 */
export type CreateBookingPaymentResponseBodyData = {
  type: string;
  title: string;
  status: number;
  detail: string;
};

/**
 * Not Found
 */
export class CreateBookingPaymentResponseBody extends SDKError {
  type: string;
  title: string;
  status: number;
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: CreateBookingPaymentResponseBodyData;

  constructor(
    err: CreateBookingPaymentResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.detail = err.detail;

    this.name = "CreateBookingPaymentResponseBody";
  }
}

/** @internal */
export const CreateBookingPaymentResponseBody$inboundSchema: z.ZodType<
  CreateBookingPaymentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number(),
  detail: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateBookingPaymentResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
