/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SDKError } from "./sdkerror.js";

/**
 * Internal Server Error
 */
export type GetBookingsBookingsResponseBodyData = {
  type: string;
  title: string;
  status: number;
  detail: string;
};

/**
 * Internal Server Error
 */
export class GetBookingsBookingsResponseBody extends SDKError {
  type: string;
  title: string;
  status: number;
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: GetBookingsBookingsResponseBodyData;

  constructor(
    err: GetBookingsBookingsResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.detail = err.detail;

    this.name = "GetBookingsBookingsResponseBody";
  }
}

/**
 * Unauthorized
 */
export type GetBookingsResponseBodyData = {
  type: string;
  title: string;
  status: number;
  detail: string;
};

/**
 * Unauthorized
 */
export class GetBookingsResponseBody extends SDKError {
  type: string;
  title: string;
  status: number;
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: GetBookingsResponseBodyData;

  constructor(
    err: GetBookingsResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    this.detail = err.detail;

    this.name = "GetBookingsResponseBody";
  }
}

/** @internal */
export const GetBookingsBookingsResponseBody$inboundSchema: z.ZodType<
  GetBookingsBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number(),
  detail: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetBookingsBookingsResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetBookingsResponseBody$inboundSchema: z.ZodType<
  GetBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number(),
  detail: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetBookingsResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
