/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateBookingPaymentPaymentsCurrency = {
  Bam: "bam",
  Bgn: "bgn",
  Chf: "chf",
  Eur: "eur",
  Gbp: "gbp",
  Nok: "nok",
  Sek: "sek",
} as const;
export type CreateBookingPaymentPaymentsCurrency = ClosedEnum<
  typeof CreateBookingPaymentPaymentsCurrency
>;

export const CreateBookingPaymentSourceAccountType = {
  Individual: "individual",
  Company: "company",
} as const;
export type CreateBookingPaymentSourceAccountType = ClosedEnum<
  typeof CreateBookingPaymentSourceAccountType
>;

export type CreateBookingPaymentSource2 = {
  object: "bank_account";
  name: string;
  number: string;
  sortCode?: string | undefined;
  accountType: CreateBookingPaymentSourceAccountType;
  bankName: string;
  country: string;
};

export type CreateBookingPaymentSource1 = {
  object: "card";
  name: string;
  number: string;
  cvc: string;
  expMonth: number;
  expYear: number;
  addressCountry: string;
  addressPostCode?: string | undefined;
};

export type CreateBookingPaymentPaymentsSource =
  | CreateBookingPaymentSource1
  | CreateBookingPaymentSource2;

export type CreateBookingPaymentPaymentsRequestRequestBody = {
  amount: number;
  currency: CreateBookingPaymentPaymentsCurrency;
  promoCode?: string | null | undefined;
  source: CreateBookingPaymentSource1 | CreateBookingPaymentSource2;
};

export type CreateBookingPaymentRequest = {
  bookingId: string;
  requestBody: CreateBookingPaymentPaymentsRequestRequestBody;
};

export const CreateBookingPaymentSourcePaymentsAccountType = {
  Individual: "individual",
  Company: "company",
} as const;
export type CreateBookingPaymentSourcePaymentsAccountType = ClosedEnum<
  typeof CreateBookingPaymentSourcePaymentsAccountType
>;

export type CreateBookingPaymentSourcePayments2 = {
  object: "bank_account";
  name: string;
  number: string;
  sortCode?: string | undefined;
  accountType: CreateBookingPaymentSourcePaymentsAccountType;
  bankName: string;
  country: string;
};

export type CreateBookingPaymentSourcePayments1 = {
  object: "card";
  name: string;
  number: string;
  cvc: string;
  expMonth: number;
  expYear: number;
  addressCountry: string;
  addressPostCode?: string | undefined;
};

export type CreateBookingPaymentPaymentsResponseSource =
  | CreateBookingPaymentSourcePayments1
  | CreateBookingPaymentSourcePayments2;

export const Status = {
  Pending: "pending",
  Succeeded: "succeeded",
  Failed: "failed",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type CreateBookingPaymentLinks = {
  booking: string;
};

/**
 * Payment successful
 */
export type CreateBookingPaymentResponseBody = {
  id: string;
  amount: number;
  currency: string;
  source:
    | CreateBookingPaymentSourcePayments1
    | CreateBookingPaymentSourcePayments2;
  status: Status;
  links: CreateBookingPaymentLinks;
};

/** @internal */
export const CreateBookingPaymentPaymentsCurrency$outboundSchema:
  z.ZodNativeEnum<typeof CreateBookingPaymentPaymentsCurrency> = z.nativeEnum(
    CreateBookingPaymentPaymentsCurrency,
  );

/** @internal */
export const CreateBookingPaymentSourceAccountType$outboundSchema:
  z.ZodNativeEnum<typeof CreateBookingPaymentSourceAccountType> = z.nativeEnum(
    CreateBookingPaymentSourceAccountType,
  );

/** @internal */
export type CreateBookingPaymentSource2$Outbound = {
  object: "bank_account";
  name: string;
  number: string;
  sort_code?: string | undefined;
  account_type: string;
  bank_name: string;
  country: string;
};

/** @internal */
export const CreateBookingPaymentSource2$outboundSchema: z.ZodType<
  CreateBookingPaymentSource2$Outbound,
  z.ZodTypeDef,
  CreateBookingPaymentSource2
> = z.object({
  object: z.literal("bank_account"),
  name: z.string(),
  number: z.string(),
  sortCode: z.string().optional(),
  accountType: CreateBookingPaymentSourceAccountType$outboundSchema,
  bankName: z.string(),
  country: z.string(),
}).transform((v) => {
  return remap$(v, {
    sortCode: "sort_code",
    accountType: "account_type",
    bankName: "bank_name",
  });
});

export function createBookingPaymentSource2ToJSON(
  createBookingPaymentSource2: CreateBookingPaymentSource2,
): string {
  return JSON.stringify(
    CreateBookingPaymentSource2$outboundSchema.parse(
      createBookingPaymentSource2,
    ),
  );
}

/** @internal */
export type CreateBookingPaymentSource1$Outbound = {
  object: "card";
  name: string;
  number: string;
  cvc: string;
  exp_month: number;
  exp_year: number;
  address_country: string;
  address_post_code?: string | undefined;
};

/** @internal */
export const CreateBookingPaymentSource1$outboundSchema: z.ZodType<
  CreateBookingPaymentSource1$Outbound,
  z.ZodTypeDef,
  CreateBookingPaymentSource1
> = z.object({
  object: z.literal("card"),
  name: z.string(),
  number: z.string(),
  cvc: z.string(),
  expMonth: z.number(),
  expYear: z.number(),
  addressCountry: z.string(),
  addressPostCode: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    expMonth: "exp_month",
    expYear: "exp_year",
    addressCountry: "address_country",
    addressPostCode: "address_post_code",
  });
});

export function createBookingPaymentSource1ToJSON(
  createBookingPaymentSource1: CreateBookingPaymentSource1,
): string {
  return JSON.stringify(
    CreateBookingPaymentSource1$outboundSchema.parse(
      createBookingPaymentSource1,
    ),
  );
}

/** @internal */
export type CreateBookingPaymentPaymentsSource$Outbound =
  | CreateBookingPaymentSource1$Outbound
  | CreateBookingPaymentSource2$Outbound;

/** @internal */
export const CreateBookingPaymentPaymentsSource$outboundSchema: z.ZodType<
  CreateBookingPaymentPaymentsSource$Outbound,
  z.ZodTypeDef,
  CreateBookingPaymentPaymentsSource
> = z.union([
  z.lazy(() => CreateBookingPaymentSource1$outboundSchema),
  z.lazy(() => CreateBookingPaymentSource2$outboundSchema),
]);

export function createBookingPaymentPaymentsSourceToJSON(
  createBookingPaymentPaymentsSource: CreateBookingPaymentPaymentsSource,
): string {
  return JSON.stringify(
    CreateBookingPaymentPaymentsSource$outboundSchema.parse(
      createBookingPaymentPaymentsSource,
    ),
  );
}

/** @internal */
export type CreateBookingPaymentPaymentsRequestRequestBody$Outbound = {
  amount: number;
  currency: string;
  promo_code?: string | null | undefined;
  source:
    | CreateBookingPaymentSource1$Outbound
    | CreateBookingPaymentSource2$Outbound;
};

/** @internal */
export const CreateBookingPaymentPaymentsRequestRequestBody$outboundSchema:
  z.ZodType<
    CreateBookingPaymentPaymentsRequestRequestBody$Outbound,
    z.ZodTypeDef,
    CreateBookingPaymentPaymentsRequestRequestBody
  > = z.object({
    amount: z.number(),
    currency: CreateBookingPaymentPaymentsCurrency$outboundSchema,
    promoCode: z.nullable(z.string()).optional(),
    source: z.union([
      z.lazy(() => CreateBookingPaymentSource1$outboundSchema),
      z.lazy(() => CreateBookingPaymentSource2$outboundSchema),
    ]),
  }).transform((v) => {
    return remap$(v, {
      promoCode: "promo_code",
    });
  });

export function createBookingPaymentPaymentsRequestRequestBodyToJSON(
  createBookingPaymentPaymentsRequestRequestBody:
    CreateBookingPaymentPaymentsRequestRequestBody,
): string {
  return JSON.stringify(
    CreateBookingPaymentPaymentsRequestRequestBody$outboundSchema.parse(
      createBookingPaymentPaymentsRequestRequestBody,
    ),
  );
}

/** @internal */
export type CreateBookingPaymentRequest$Outbound = {
  bookingId: string;
  RequestBody: CreateBookingPaymentPaymentsRequestRequestBody$Outbound;
};

/** @internal */
export const CreateBookingPaymentRequest$outboundSchema: z.ZodType<
  CreateBookingPaymentRequest$Outbound,
  z.ZodTypeDef,
  CreateBookingPaymentRequest
> = z.object({
  bookingId: z.string(),
  requestBody: z.lazy(() =>
    CreateBookingPaymentPaymentsRequestRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createBookingPaymentRequestToJSON(
  createBookingPaymentRequest: CreateBookingPaymentRequest,
): string {
  return JSON.stringify(
    CreateBookingPaymentRequest$outboundSchema.parse(
      createBookingPaymentRequest,
    ),
  );
}

/** @internal */
export const CreateBookingPaymentSourcePaymentsAccountType$inboundSchema:
  z.ZodNativeEnum<typeof CreateBookingPaymentSourcePaymentsAccountType> = z
    .nativeEnum(CreateBookingPaymentSourcePaymentsAccountType);

/** @internal */
export const CreateBookingPaymentSourcePayments2$inboundSchema: z.ZodType<
  CreateBookingPaymentSourcePayments2,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.literal("bank_account"),
  name: z.string(),
  number: z.string(),
  sort_code: z.string().optional(),
  account_type: CreateBookingPaymentSourcePaymentsAccountType$inboundSchema,
  bank_name: z.string(),
  country: z.string(),
}).transform((v) => {
  return remap$(v, {
    "sort_code": "sortCode",
    "account_type": "accountType",
    "bank_name": "bankName",
  });
});

export function createBookingPaymentSourcePayments2FromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingPaymentSourcePayments2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingPaymentSourcePayments2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingPaymentSourcePayments2' from JSON`,
  );
}

/** @internal */
export const CreateBookingPaymentSourcePayments1$inboundSchema: z.ZodType<
  CreateBookingPaymentSourcePayments1,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.literal("card"),
  name: z.string(),
  number: z.string(),
  cvc: z.string(),
  exp_month: z.number(),
  exp_year: z.number(),
  address_country: z.string(),
  address_post_code: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "exp_month": "expMonth",
    "exp_year": "expYear",
    "address_country": "addressCountry",
    "address_post_code": "addressPostCode",
  });
});

export function createBookingPaymentSourcePayments1FromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingPaymentSourcePayments1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingPaymentSourcePayments1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingPaymentSourcePayments1' from JSON`,
  );
}

/** @internal */
export const CreateBookingPaymentPaymentsResponseSource$inboundSchema:
  z.ZodType<CreateBookingPaymentPaymentsResponseSource, z.ZodTypeDef, unknown> =
    z.union([
      z.lazy(() => CreateBookingPaymentSourcePayments1$inboundSchema),
      z.lazy(() => CreateBookingPaymentSourcePayments2$inboundSchema),
    ]);

export function createBookingPaymentPaymentsResponseSourceFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateBookingPaymentPaymentsResponseSource,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingPaymentPaymentsResponseSource$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateBookingPaymentPaymentsResponseSource' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const CreateBookingPaymentLinks$inboundSchema: z.ZodType<
  CreateBookingPaymentLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  booking: z.string(),
});

export function createBookingPaymentLinksFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingPaymentLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingPaymentLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingPaymentLinks' from JSON`,
  );
}

/** @internal */
export const CreateBookingPaymentResponseBody$inboundSchema: z.ZodType<
  CreateBookingPaymentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  amount: z.number(),
  currency: z.string(),
  source: z.union([
    z.lazy(() => CreateBookingPaymentSourcePayments1$inboundSchema),
    z.lazy(() => CreateBookingPaymentSourcePayments2$inboundSchema),
  ]),
  status: Status$inboundSchema,
  links: z.lazy(() => CreateBookingPaymentLinks$inboundSchema),
});

export function createBookingPaymentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingPaymentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingPaymentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingPaymentResponseBody' from JSON`,
  );
}
