/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteUsersByIdRequest = {
  id: string;
};

/** @internal */
export const DeleteUsersByIdRequest$inboundSchema: z.ZodType<
  DeleteUsersByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteUsersByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteUsersByIdRequest$outboundSchema: z.ZodType<
  DeleteUsersByIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteUsersByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteUsersByIdRequest$ {
  /** @deprecated use `DeleteUsersByIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteUsersByIdRequest$inboundSchema;
  /** @deprecated use `DeleteUsersByIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteUsersByIdRequest$outboundSchema;
  /** @deprecated use `DeleteUsersByIdRequest$Outbound` instead. */
  export type Outbound = DeleteUsersByIdRequest$Outbound;
}

export function deleteUsersByIdRequestToJSON(
  deleteUsersByIdRequest: DeleteUsersByIdRequest,
): string {
  return JSON.stringify(
    DeleteUsersByIdRequest$outboundSchema.parse(deleteUsersByIdRequest),
  );
}

export function deleteUsersByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteUsersByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteUsersByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteUsersByIdRequest' from JSON`,
  );
}
