/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteBookingRequest = {
  bookingId: string;
};

/** @internal */
export type DeleteBookingRequest$Outbound = {
  bookingId: string;
};

/** @internal */
export const DeleteBookingRequest$outboundSchema: z.ZodType<
  DeleteBookingRequest$Outbound,
  z.ZodTypeDef,
  DeleteBookingRequest
> = z.object({
  bookingId: z.string(),
});

export function deleteBookingRequestToJSON(
  deleteBookingRequest: DeleteBookingRequest,
): string {
  return JSON.stringify(
    DeleteBookingRequest$outboundSchema.parse(deleteBookingRequest),
  );
}
