/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBookingsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
};

/**
 * A booking for a train trip.
 */
export type GetBookingsData = {
  id: string;
  tripId: string;
  passengerName: string;
  hasBicycle: boolean;
  hasDog: boolean;
};

export type GetBookingsLinks = {
  self: string;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * A list of bookings
 */
export type GetBookingsResponseBody = {
  data: Array<GetBookingsData>;
  links: GetBookingsLinks;
};

/** @internal */
export type GetBookingsRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const GetBookingsRequest$outboundSchema: z.ZodType<
  GetBookingsRequest$Outbound,
  z.ZodTypeDef,
  GetBookingsRequest
> = z.object({
  page: z.number().default(1),
  limit: z.number().default(10),
});

export function getBookingsRequestToJSON(
  getBookingsRequest: GetBookingsRequest,
): string {
  return JSON.stringify(
    GetBookingsRequest$outboundSchema.parse(getBookingsRequest),
  );
}

/** @internal */
export const GetBookingsData$inboundSchema: z.ZodType<
  GetBookingsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  trip_id: z.string(),
  passenger_name: z.string(),
  has_bicycle: z.boolean(),
  has_dog: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "passenger_name": "passengerName",
    "has_bicycle": "hasBicycle",
    "has_dog": "hasDog",
  });
});

export function getBookingsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsData' from JSON`,
  );
}

/** @internal */
export const GetBookingsLinks$inboundSchema: z.ZodType<
  GetBookingsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getBookingsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsLinks' from JSON`,
  );
}

/** @internal */
export const GetBookingsResponseBody$inboundSchema: z.ZodType<
  GetBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => GetBookingsData$inboundSchema)),
  links: z.lazy(() => GetBookingsLinks$inboundSchema),
});

export function getBookingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsResponseBody' from JSON`,
  );
}
