/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteBurgerRequest = {
  burgerId: number;
};

/** @internal */
export const DeleteBurgerRequest$inboundSchema: z.ZodType<
  DeleteBurgerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  burger_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "burger_id": "burgerId",
  });
});

/** @internal */
export type DeleteBurgerRequest$Outbound = {
  burger_id: number;
};

/** @internal */
export const DeleteBurgerRequest$outboundSchema: z.ZodType<
  DeleteBurgerRequest$Outbound,
  z.ZodTypeDef,
  DeleteBurgerRequest
> = z.object({
  burgerId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    burgerId: "burger_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteBurgerRequest$ {
  /** @deprecated use `DeleteBurgerRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteBurgerRequest$inboundSchema;
  /** @deprecated use `DeleteBurgerRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteBurgerRequest$outboundSchema;
  /** @deprecated use `DeleteBurgerRequest$Outbound` instead. */
  export type Outbound = DeleteBurgerRequest$Outbound;
}

export function deleteBurgerRequestToJSON(
  deleteBurgerRequest: DeleteBurgerRequest,
): string {
  return JSON.stringify(
    DeleteBurgerRequest$outboundSchema.parse(deleteBurgerRequest),
  );
}

export function deleteBurgerRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBurgerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBurgerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBurgerRequest' from JSON`,
  );
}
