// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteOrderOrdersOrderIDDeleteRequest struct {
	OrderID int64 `pathParam:"style=simple,explode=false,name=order_id"`
}

func (o *DeleteOrderOrdersOrderIDDeleteRequest) GetOrderID() int64 {
	if o == nil {
		return 0
	}
	return o.OrderID
}

type DeleteOrderOrdersOrderIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteOrderOrdersOrderIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
