/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Drivers } from "./drivers.js";
import { Laps } from "./laps.js";
import { Root } from "./root.js";

export class RacingLapCounter extends ClientSDK {
  private _root?: Root;
  get root(): Root {
    return (this._root ??= new Root(this._options));
  }

  private _drivers?: Drivers;
  get drivers(): Drivers {
    return (this._drivers ??= new Drivers(this._options));
  }

  private _laps?: Laps;
  get laps(): Laps {
    return (this._laps ??= new Laps(this._options));
  }
}
