// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateCollectionGlobals struct {
	TenantID     *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	DatabaseName *string `pathParam:"style=simple,explode=false,name=database_name"`
}

func (o *CreateCollectionGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CreateCollectionGlobals) GetDatabaseName() *string {
	if o == nil {
		return nil
	}
	return o.DatabaseName
}

type CreateCollectionRequest struct {
	// Tenant ID
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Database name containing the new collection
	DatabaseName            *string                            `pathParam:"style=simple,explode=false,name=database_name"`
	CreateCollectionPayload components.CreateCollectionPayload `request:"mediaType=application/json"`
}

func (o *CreateCollectionRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CreateCollectionRequest) GetDatabaseName() *string {
	if o == nil {
		return nil
	}
	return o.DatabaseName
}

func (o *CreateCollectionRequest) GetCreateCollectionPayload() components.CreateCollectionPayload {
	if o == nil {
		return components.CreateCollectionPayload{}
	}
	return o.CreateCollectionPayload
}

type CreateCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Collection created successfully
	Collection *components.Collection
}

func (o *CreateCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCollectionResponse) GetCollection() *components.Collection {
	if o == nil {
		return nil
	}
	return o.Collection
}
