// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateDatabaseGlobals struct {
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
}

func (o *CreateDatabaseGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

type CreateDatabaseRequest struct {
	// Tenant ID to associate with the new database
	TenantID              *string                          `pathParam:"style=simple,explode=false,name=tenant_id"`
	CreateDatabasePayload components.CreateDatabasePayload `request:"mediaType=application/json"`
}

func (o *CreateDatabaseRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CreateDatabaseRequest) GetCreateDatabasePayload() components.CreateDatabasePayload {
	if o == nil {
		return components.CreateDatabasePayload{}
	}
	return o.CreateDatabasePayload
}

type CreateDatabaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Database created successfully
	CreateDatabaseResponse *components.CreateDatabaseResponse
}

func (o *CreateDatabaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateDatabaseResponse) GetCreateDatabaseResponse() *components.CreateDatabaseResponse {
	if o == nil {
		return nil
	}
	return o.CreateDatabaseResponse
}
