// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteCollectionGlobals struct {
	TenantID     *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	DatabaseName *string `pathParam:"style=simple,explode=false,name=database_name"`
}

func (o *DeleteCollectionGlobals) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DeleteCollectionGlobals) GetDatabaseName() *string {
	if o == nil {
		return nil
	}
	return o.DatabaseName
}

type DeleteCollectionRequest struct {
	// Tenant ID
	TenantID *string `pathParam:"style=simple,explode=false,name=tenant_id"`
	// Database name
	DatabaseName *string `pathParam:"style=simple,explode=false,name=database_name"`
	// UUID of the collection to delete
	CollectionID string `pathParam:"style=simple,explode=false,name=collection_id"`
}

func (o *DeleteCollectionRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *DeleteCollectionRequest) GetDatabaseName() *string {
	if o == nil {
		return nil
	}
	return o.DatabaseName
}

func (o *DeleteCollectionRequest) GetCollectionID() string {
	if o == nil {
		return ""
	}
	return o.CollectionID
}

type DeleteCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Collection deleted successfully
	UpdateCollectionResponse *components.UpdateCollectionResponse
}

func (o *DeleteCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteCollectionResponse) GetUpdateCollectionResponse() *components.UpdateCollectionResponse {
	if o == nil {
		return nil
	}
	return o.UpdateCollectionResponse
}
