"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BurgerUpdateTypedDict(TypedDict):
    r"""Fields to update a burger"""

    name: NotRequired[str]
    r"""The name of the burger"""
    description: NotRequired[str]
    r"""The description of the burger"""


class BurgerUpdate(BaseModel):
    r"""Fields to update a burger"""

    name: Optional[str] = None
    r"""The name of the burger"""

    description: Optional[str] = None
    r"""The description of the burger"""
