"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OrderCreateTypedDict(TypedDict):
    r"""Fields to create an order"""

    burger_ids: List[int]
    r"""List of burger ids in the order"""
    table: int
    r"""Table number for the order"""
    note: NotRequired[str]
    r"""Note for the order"""


class OrderCreate(BaseModel):
    r"""Fields to create an order"""

    burger_ids: List[int]
    r"""List of burger ids in the order"""

    table: int
    r"""Table number for the order"""

    note: Optional[str] = None
    r"""Note for the order"""
