"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .orderstatus import OrderStatus
from openapi.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OrderUpdateTypedDict(TypedDict):
    r"""Fields to update an order"""

    burger_ids: NotRequired[List[int]]
    r"""List of burger ids in the order"""
    table: NotRequired[int]
    r"""Table number for the order"""
    status: NotRequired[OrderStatus]
    r"""Status of the order"""
    note: NotRequired[str]
    r"""Note for the order"""


class OrderUpdate(BaseModel):
    r"""Fields to update an order"""

    burger_ids: Optional[List[int]] = None
    r"""List of burger ids in the order"""

    table: Optional[int] = None
    r"""Table number for the order"""

    status: Optional[OrderStatus] = None
    r"""Status of the order"""

    note: Optional[str] = None
    r"""Note for the order"""
