/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsDeleteRecords } from "../../funcs/collectionsDeleteRecords.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CollectionDeleteRequest$inboundSchema,
};

export const tool$collectionsDeleteRecords: ToolDefinition<typeof args> = {
  name: "collections_delete-records",
  description:
    `Deletes records in a collection. Can filter by IDs or metadata.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsDeleteRecords(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
