/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsCreate } from "../../funcs/collectionsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCollectionRequest$inboundSchema,
};

export const tool$collectionsCreate: ToolDefinition<typeof args> = {
  name: "collections_create",
  description: `Creates a new collection under the specified database.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
