/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsRetrieveRecords } from "../../funcs/collectionsRetrieveRecords.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CollectionGetRequest$inboundSchema,
};

export const tool$collectionsRetrieveRecords: ToolDefinition<typeof args> = {
  name: "collections_retrieve-records",
  description: `Retrieves records from a collection by ID or metadata filter.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectionsRetrieveRecords(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
