/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { databasesList } from "../../funcs/databasesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListDatabasesRequest$inboundSchema,
};

export const tool$databasesList: ToolDefinition<typeof args> = {
  name: "databases_list",
  description: `Lists all databases for a given tenant.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await databasesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
