/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemGetHeartbeat } from "../../funcs/systemGetHeartbeat.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$systemGetHeartbeat: ToolDefinition = {
  name: "system_get-heartbeat",
  description:
    `Heartbeat endpoint that returns a nanosecond timestamp of the current time. Useful for making sure the client remains connected.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await systemGetHeartbeat(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
