/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const RevisionContentsMetadataType = {
  OpenapiBundle: "OPENAPI_BUNDLE",
  OpenapiOverlay: "OPENAPI_OVERLAY",
} as const;
export type RevisionContentsMetadataType = ClosedEnum<
  typeof RevisionContentsMetadataType
>;

export type RevisionContentsMetadata = {
  type: RevisionContentsMetadataType;
  /**
   * The workspace ID
   */
  workspaceId: string;
  /**
   * The fully qualified namespace
   */
  namespace: string;
  /**
   * The digest of the parent bundle
   */
  revisionDigest: string;
  /**
   * The OAS title
   */
  title: string;
  /**
   * The OAS description
   */
  description: string;
  /**
   * The OAS version
   */
  version: string;
  /**
   * The hash of the contents
   */
  hash: string;
  /**
   * The tags contained in the OAS -- NOT the OCI tags. Will be empty if the OAS is an overlay.
   */
  tags: Array<string>;
  /**
   * The operation IDs contained in the OAS. Will be empty if the OAS is an overlay.
   */
  operationIds: Array<string>;
  /**
   * The number of overlay actions in the OAS. Will be 0 if the OAS is not an overlay.
   */
  numOverlayActions: number;
  /**
   * Whether the OAS contains code samples.
   */
  containsCodeSamples: boolean;
  createdAt: Date;
};

/** @internal */
export const RevisionContentsMetadataType$inboundSchema: z.ZodNativeEnum<
  typeof RevisionContentsMetadataType
> = z.nativeEnum(RevisionContentsMetadataType);

/** @internal */
export const RevisionContentsMetadataType$outboundSchema: z.ZodNativeEnum<
  typeof RevisionContentsMetadataType
> = RevisionContentsMetadataType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RevisionContentsMetadataType$ {
  /** @deprecated use `RevisionContentsMetadataType$inboundSchema` instead. */
  export const inboundSchema = RevisionContentsMetadataType$inboundSchema;
  /** @deprecated use `RevisionContentsMetadataType$outboundSchema` instead. */
  export const outboundSchema = RevisionContentsMetadataType$outboundSchema;
}

/** @internal */
export const RevisionContentsMetadata$inboundSchema: z.ZodType<
  RevisionContentsMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: RevisionContentsMetadataType$inboundSchema,
  workspace_id: z.string(),
  namespace: z.string(),
  revision_digest: z.string(),
  title: z.string(),
  description: z.string(),
  version: z.string(),
  hash: z.string(),
  tags: z.array(z.string()),
  operation_ids: z.array(z.string()),
  num_overlay_actions: z.number().int(),
  contains_code_samples: z.boolean(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "revision_digest": "revisionDigest",
    "operation_ids": "operationIds",
    "num_overlay_actions": "numOverlayActions",
    "contains_code_samples": "containsCodeSamples",
    "created_at": "createdAt",
  });
});

/** @internal */
export type RevisionContentsMetadata$Outbound = {
  type: string;
  workspace_id: string;
  namespace: string;
  revision_digest: string;
  title: string;
  description: string;
  version: string;
  hash: string;
  tags: Array<string>;
  operation_ids: Array<string>;
  num_overlay_actions: number;
  contains_code_samples: boolean;
  created_at: string;
};

/** @internal */
export const RevisionContentsMetadata$outboundSchema: z.ZodType<
  RevisionContentsMetadata$Outbound,
  z.ZodTypeDef,
  RevisionContentsMetadata
> = z.object({
  type: RevisionContentsMetadataType$outboundSchema,
  workspaceId: z.string(),
  namespace: z.string(),
  revisionDigest: z.string(),
  title: z.string(),
  description: z.string(),
  version: z.string(),
  hash: z.string(),
  tags: z.array(z.string()),
  operationIds: z.array(z.string()),
  numOverlayActions: z.number().int(),
  containsCodeSamples: z.boolean(),
  createdAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
    revisionDigest: "revision_digest",
    operationIds: "operation_ids",
    numOverlayActions: "num_overlay_actions",
    containsCodeSamples: "contains_code_samples",
    createdAt: "created_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RevisionContentsMetadata$ {
  /** @deprecated use `RevisionContentsMetadata$inboundSchema` instead. */
  export const inboundSchema = RevisionContentsMetadata$inboundSchema;
  /** @deprecated use `RevisionContentsMetadata$outboundSchema` instead. */
  export const outboundSchema = RevisionContentsMetadata$outboundSchema;
  /** @deprecated use `RevisionContentsMetadata$Outbound` instead. */
  export type Outbound = RevisionContentsMetadata$Outbound;
}

export function revisionContentsMetadataToJSON(
  revisionContentsMetadata: RevisionContentsMetadata,
): string {
  return JSON.stringify(
    RevisionContentsMetadata$outboundSchema.parse(revisionContentsMetadata),
  );
}

export function revisionContentsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<RevisionContentsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevisionContentsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevisionContentsMetadata' from JSON`,
  );
}
