/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coffeeTypesList } from "../../funcs/coffeeTypesList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$coffeeTypesList: ToolDefinition = {
  name: "coffee-types_list",
  description: `Get Coffee Types

Retrieve all available coffee types.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await coffeeTypesList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
