/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { coffeeTypesDelete } from "../../funcs/coffeeTypesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteCoffeeTypeRequest$inboundSchema,
};

export const tool$coffeeTypesDelete: ToolDefinition<typeof args> = {
  name: "coffee-types_delete",
  description: `Delete Coffee Type

Delete a coffee type.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await coffeeTypesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
