/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { orderCreateOrder } from "../../funcs/orderCreateOrder.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.OrderCreate$inboundSchema,
};

export const tool$orderCreateOrder: ToolDefinition<typeof args> = {
  name: "order-create-order",
  description: `Create Order

Create an order`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await orderCreateOrder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
