workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Ping Pong API:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/ping-pong-api
targets:
    msw-example:
        target: typescript
        source: Ping Pong API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/ping-pong-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
