/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authGetIdentity } from "../funcs/authGetIdentity.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Retrieves the current user's identity, tenant, and databases.
   */
  async getIdentity(
    options?: RequestOptions,
  ): Promise<components.GetUserIdentityResponse> {
    return unwrapAsync(authGetIdentity(
      this,
      options,
    ));
  }
}
