/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auth } from "./auth.js";
import { Collections } from "./collections.js";
import { Databases } from "./databases.js";
import { System } from "./system.js";
import { Tenants } from "./tenants.js";

export class API extends ClientSDK {
  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _system?: System;
  get system(): System {
    return (this._system ??= new System(this._options));
  }

  private _tenants?: Tenants;
  get tenants(): Tenants {
    return (this._tenants ??= new Tenants(this._options));
  }

  private _databases?: Databases;
  get databases(): Databases {
    return (this._databases ??= new Databases(this._options));
  }

  private _collections?: Collections;
  get collections(): Collections {
    return (this._collections ??= new Collections(this._options));
  }
}
