/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCoffeeTypeRequest = {
  /**
   * The ID of the coffee type to operate on
   */
  typeId: number;
};

/** @internal */
export const GetCoffeeTypeRequest$inboundSchema: z.ZodType<
  GetCoffeeTypeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "type_id": "typeId",
  });
});

/** @internal */
export type GetCoffeeTypeRequest$Outbound = {
  type_id: number;
};

/** @internal */
export const GetCoffeeTypeRequest$outboundSchema: z.ZodType<
  GetCoffeeTypeRequest$Outbound,
  z.ZodTypeDef,
  GetCoffeeTypeRequest
> = z.object({
  typeId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    typeId: "type_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCoffeeTypeRequest$ {
  /** @deprecated use `GetCoffeeTypeRequest$inboundSchema` instead. */
  export const inboundSchema = GetCoffeeTypeRequest$inboundSchema;
  /** @deprecated use `GetCoffeeTypeRequest$outboundSchema` instead. */
  export const outboundSchema = GetCoffeeTypeRequest$outboundSchema;
  /** @deprecated use `GetCoffeeTypeRequest$Outbound` instead. */
  export type Outbound = GetCoffeeTypeRequest$Outbound;
}

export function getCoffeeTypeRequestToJSON(
  getCoffeeTypeRequest: GetCoffeeTypeRequest,
): string {
  return JSON.stringify(
    GetCoffeeTypeRequest$outboundSchema.parse(getCoffeeTypeRequest),
  );
}

export function getCoffeeTypeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCoffeeTypeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCoffeeTypeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCoffeeTypeRequest' from JSON`,
  );
}
