/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrderRequest = {
  /**
   * The ID of the order to operate on
   */
  orderId: number;
};

/** @internal */
export const GetOrderRequest$inboundSchema: z.ZodType<
  GetOrderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  order_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "order_id": "orderId",
  });
});

/** @internal */
export type GetOrderRequest$Outbound = {
  order_id: number;
};

/** @internal */
export const GetOrderRequest$outboundSchema: z.ZodType<
  GetOrderRequest$Outbound,
  z.ZodTypeDef,
  GetOrderRequest
> = z.object({
  orderId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    orderId: "order_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderRequest$ {
  /** @deprecated use `GetOrderRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrderRequest$inboundSchema;
  /** @deprecated use `GetOrderRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrderRequest$outboundSchema;
  /** @deprecated use `GetOrderRequest$Outbound` instead. */
  export type Outbound = GetOrderRequest$Outbound;
}

export function getOrderRequestToJSON(
  getOrderRequest: GetOrderRequest,
): string {
  return JSON.stringify(GetOrderRequest$outboundSchema.parse(getOrderRequest));
}

export function getOrderRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderRequest' from JSON`,
  );
}
