/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Payment status.
 */
export const Status = {
  Pending: "pending",
  Succeeded: "succeeded",
  Failed: "failed",
} as const;
/**
 * Payment status.
 */
export type Status = ClosedEnum<typeof Status>;

export type BookingPayment = {
  /**
   * Payment identifier.
   */
  id: string;
  /**
   * Payment amount.
   */
  amount: number;
  /**
   * Lowercase ISO currency code.
   */
  currency: string;
  /**
   * Payment status.
   */
  status: Status;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const BookingPayment$inboundSchema: z.ZodType<
  BookingPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  amount: z.number(),
  currency: z.string(),
  status: Status$inboundSchema,
});

export function bookingPaymentFromJSON(
  jsonString: string,
): SafeParseResult<BookingPayment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BookingPayment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BookingPayment' from JSON`,
  );
}
