/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { artifactsCreateRemoteSource } from "../funcs/artifactsCreateRemoteSource.js";
import { artifactsGetBlob } from "../funcs/artifactsGetBlob.js";
import { artifactsGetManifest } from "../funcs/artifactsGetManifest.js";
import { artifactsGetNamespaces } from "../funcs/artifactsGetNamespaces.js";
import { artifactsGetRevisions } from "../funcs/artifactsGetRevisions.js";
import { artifactsGetTags } from "../funcs/artifactsGetTags.js";
import { artifactsListRemoteSources } from "../funcs/artifactsListRemoteSources.js";
import { artifactsPostTags } from "../funcs/artifactsPostTags.js";
import { artifactsPreflight } from "../funcs/artifactsPreflight.js";
import { artifactsSetArchived } from "../funcs/artifactsSetArchived.js";
import { artifactsSetVisibility } from "../funcs/artifactsSetVisibility.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Artifacts extends ClientSDK {
  /**
   * Get access token for communicating with OCI distribution endpoints
   */
  async preflight(
    request?: components.PreflightRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.PreflightToken> {
    return unwrapAsync(artifactsPreflight(
      this,
      request,
      options,
    ));
  }

  /**
   * Each namespace contains many revisions.
   */
  async getNamespaces(
    options?: RequestOptions,
  ): Promise<components.GetNamespacesResponse> {
    return unwrapAsync(artifactsGetNamespaces(
      this,
      options,
    ));
  }

  /**
   * Set whether a namespace is archived
   */
  async setArchived(
    request: operations.ArchiveNamespaceRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(artifactsSetArchived(
      this,
      request,
      options,
    ));
  }

  async getRevisions(
    request: operations.GetRevisionsRequest,
    options?: RequestOptions,
  ): Promise<components.GetRevisionsResponse> {
    return unwrapAsync(artifactsGetRevisions(
      this,
      request,
      options,
    ));
  }

  async getTags(
    request: operations.GetTagsRequest,
    options?: RequestOptions,
  ): Promise<components.GetTagsResponse> {
    return unwrapAsync(artifactsGetTags(
      this,
      request,
      options,
    ));
  }

  /**
   * Add tags to an existing revision
   */
  async postTags(
    request: operations.PostTagsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(artifactsPostTags(
      this,
      request,
      options,
    ));
  }

  /**
   * Set visibility of a namespace with an existing metadata entry
   */
  async setVisibility(
    request: operations.SetVisibilityRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(artifactsSetVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * Get remote sources attached to a particular namespace
   */
  async listRemoteSources(
    request: operations.ListRemoteSourcesRequest,
    options?: RequestOptions,
  ): Promise<components.RemoteSource> {
    return unwrapAsync(artifactsListRemoteSources(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure a new remote source
   */
  async createRemoteSource(
    request?: components.RemoteSource | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(artifactsCreateRemoteSource(
      this,
      request,
      options,
    ));
  }

  /**
   * Get manifest for a particular reference
   */
  async getManifest(
    request: operations.GetManifestRequest,
    options?: RequestOptions,
  ): Promise<components.Manifest> {
    return unwrapAsync(artifactsGetManifest(
      this,
      request,
      options,
    ));
  }

  /**
   * Get blob for a particular digest
   */
  async getBlob(
    request: operations.GetBlobRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(artifactsGetBlob(
      this,
      request,
      options,
    ));
  }
}
