/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type CreateBookingRequestBody = {
  hasBicycle?: boolean | undefined;
  hasDog?: boolean | undefined;
  passengerName: string;
  tripId: string;
};

/** @internal */
export type CreateBookingRequestBody$Outbound = {
  has_bicycle: boolean;
  has_dog: boolean;
  passenger_name: string;
  trip_id: string;
};

/** @internal */
export const CreateBookingRequestBody$outboundSchema: z.ZodType<
  CreateBookingRequestBody$Outbound,
  z.ZodTypeDef,
  CreateBookingRequestBody
> = z.object({
  hasBicycle: z.boolean().default(false),
  hasDog: z.boolean().default(false),
  passengerName: z.string(),
  tripId: z.string(),
}).transform((v) => {
  return remap$(v, {
    hasBicycle: "has_bicycle",
    hasDog: "has_dog",
    passengerName: "passenger_name",
    tripId: "trip_id",
  });
});

export function createBookingRequestBodyToJSON(
  createBookingRequestBody: CreateBookingRequestBody,
): string {
  return JSON.stringify(
    CreateBookingRequestBody$outboundSchema.parse(createBookingRequestBody),
  );
}
