/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetStationsRequest = {
  coordinates?: string | undefined;
  country?: string | undefined;
  limit?: number | undefined;
  page?: number | undefined;
  search?: string | undefined;
};

export type GetStationsLinks = {
  next?: string | undefined;
  prev?: string | undefined;
  self?: string | undefined;
};

/**
 * Default Response
 */
export type GetStationsResponseBody = {
  data?: Array<shared.Station> | undefined;
  links?: GetStationsLinks | undefined;
};

/** @internal */
export type GetStationsRequest$Outbound = {
  coordinates?: string | undefined;
  country?: string | undefined;
  limit: number;
  page: number;
  search?: string | undefined;
};

/** @internal */
export const GetStationsRequest$outboundSchema: z.ZodType<
  GetStationsRequest$Outbound,
  z.ZodTypeDef,
  GetStationsRequest
> = z.object({
  coordinates: z.string().optional(),
  country: z.string().optional(),
  limit: z.number().int().default(10),
  page: z.number().int().default(1),
  search: z.string().optional(),
});

export function getStationsRequestToJSON(
  getStationsRequest: GetStationsRequest,
): string {
  return JSON.stringify(
    GetStationsRequest$outboundSchema.parse(getStationsRequest),
  );
}

/** @internal */
export const GetStationsLinks$inboundSchema: z.ZodType<
  GetStationsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  next: z.string().optional(),
  prev: z.string().optional(),
  self: z.string().optional(),
});

export function getStationsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsLinks' from JSON`,
  );
}

/** @internal */
export const GetStationsResponseBody$inboundSchema: z.ZodType<
  GetStationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(shared.Station$inboundSchema).optional(),
  links: z.lazy(() => GetStationsLinks$inboundSchema).optional(),
});

export function getStationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsResponseBody' from JSON`,
  );
}
