/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { driversDeleteDriver } from "../../funcs/driversDeleteDriver.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteDriverRequest$inboundSchema,
};

export const tool$driversDeleteDriver: ToolDefinition<typeof args> = {
  name: "drivers-delete-driver",
  description: `Delete a driver

Delete a racing driver by ID, including all associated lap records`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await driversDeleteDriver(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
