/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { driversUpdateDriver } from "../../funcs/driversUpdateDriver.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateDriverRequest$inboundSchema,
};

export const tool$driversUpdateDriver: ToolDefinition<typeof args> = {
  name: "drivers-update-driver",
  description: `Update a driver

Update a racing driver's details by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await driversUpdateDriver(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
