openapi: 3.1.0
info:
  title: Users API
  description: Development documentation
  version: 1.0.0
externalDocs:
  description: Find out more about Users API
  url: www.example.com
servers:
  - url: http://localhost:3000/
    description: Development server
x-speakeasy-retries:
  strategy: backoff
  backoff:
    initialInterval: 500
    maxInterval: 60000
    maxElapsedTime: 3600000
    exponent: 1.5
  statusCodes:
    - 5XX
  retryConnectionErrors: true
tags:
  - name: Users
    description: Users operations
    externalDocs:
      description: Find more info here
      url: https://example.com
paths:
  /users:
    get:
      operationId: getUsers
      description: Get all users
      tags:
        - Users
      x-speakeasy-retries:
        strategy: backoff
        backoff:
          initialInterval: 300
          maxInterval: 40000
          maxElapsedTime: 3000000
          exponent: 1.2
        statusCodes:
          - 5XX
        retryConnectionErrors: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSelect'
          description: The list of users
    post:
      operationId: createUser
      description: Create a user
      tags:
        - Users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSelect'
          description: The created user
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createMessageObject'
          description: User not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createError'
          description: The validation error(s)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInsert'
  /users/{id}:
    get:
      operationId: getUser
      description: Get a user by ID
      tags:
        - Users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSelect'
          description: The requested user
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createMessageObject'
          description: User not found
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createError'
          description: Invalid id error
      parameters:
        - in: path
          name: id
          schema:
            type: string
            minLength: 3
          required: true
components:
  schemas:
    UserSelect:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: number
      required:
        - id
        - name
        - age
      description: User object
    createMessageObject:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      description: Message response
    createError:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: object
          properties:
            issues:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                  path:
                    type: array
                    items:
                      anyOf:
                        - type: string
                        - type: number
                  message:
                    type: string
                required:
                  - code
                  - path
            name:
              type: string
          required:
            - issues
            - name
      required:
        - success
        - error
      description: Error response
    UserInsert:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
      required:
        - name
        - age
      description: User creation data
