/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getPing } from "../funcs/getPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class MswExample extends ClientSDK {
  /**
   * Ping endpoint
   *
   * @remarks
   * Returns a pong response
   */
  async getPing(
    request?: operations.GetPingRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetPingResponseBody> {
    return unwrapAsync(getPing(
      this,
      request,
      options,
    ));
  }
}
