/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreatePaymentSecurity = {
  oAuth2?: string | undefined;
  bearerAuth?: string | undefined;
};

export type CreatePaymentRequest = {
  bookingId: string;
};

/** @internal */
export type CreatePaymentSecurity$Outbound = {
  OAuth2?: string | undefined;
  BearerAuth?: string | undefined;
};

/** @internal */
export const CreatePaymentSecurity$outboundSchema: z.ZodType<
  CreatePaymentSecurity$Outbound,
  z.ZodTypeDef,
  CreatePaymentSecurity
> = z.object({
  oAuth2: z.string().optional(),
  bearerAuth: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    oAuth2: "OAuth2",
    bearerAuth: "BearerAuth",
  });
});

export function createPaymentSecurityToJSON(
  createPaymentSecurity: CreatePaymentSecurity,
): string {
  return JSON.stringify(
    CreatePaymentSecurity$outboundSchema.parse(createPaymentSecurity),
  );
}

/** @internal */
export type CreatePaymentRequest$Outbound = {
  bookingId: string;
};

/** @internal */
export const CreatePaymentRequest$outboundSchema: z.ZodType<
  CreatePaymentRequest$Outbound,
  z.ZodTypeDef,
  CreatePaymentRequest
> = z.object({
  bookingId: z.string(),
});

export function createPaymentRequestToJSON(
  createPaymentRequest: CreatePaymentRequest,
): string {
  return JSON.stringify(
    CreatePaymentRequest$outboundSchema.parse(createPaymentRequest),
  );
}
