/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetBookingSecurity = {
  oAuth2?: string | undefined;
  bearerAuth?: string | undefined;
};

export type GetBookingRequest = {
  bookingId: string;
};

/** @internal */
export type GetBookingSecurity$Outbound = {
  OAuth2?: string | undefined;
  BearerAuth?: string | undefined;
};

/** @internal */
export const GetBookingSecurity$outboundSchema: z.ZodType<
  GetBookingSecurity$Outbound,
  z.ZodTypeDef,
  GetBookingSecurity
> = z.object({
  oAuth2: z.string().optional(),
  bearerAuth: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    oAuth2: "OAuth2",
    bearerAuth: "BearerAuth",
  });
});

export function getBookingSecurityToJSON(
  getBookingSecurity: GetBookingSecurity,
): string {
  return JSON.stringify(
    GetBookingSecurity$outboundSchema.parse(getBookingSecurity),
  );
}

/** @internal */
export type GetBookingRequest$Outbound = {
  bookingId: string;
};

/** @internal */
export const GetBookingRequest$outboundSchema: z.ZodType<
  GetBookingRequest$Outbound,
  z.ZodTypeDef,
  GetBookingRequest
> = z.object({
  bookingId: z.string(),
});

export function getBookingRequestToJSON(
  getBookingRequest: GetBookingRequest,
): string {
  return JSON.stringify(
    GetBookingRequest$outboundSchema.parse(getBookingRequest),
  );
}
