/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCreateBookingPayment } from "../funcs/paymentsCreateBookingPayment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * Pay for a booking
   *
   * @remarks
   * A payment attempt confirms the booking and enables ticket retrieval.
   */
  async createBookingPayment(
    request: operations.CreateBookingPaymentRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateBookingPaymentResponseBody> {
    return unwrapAsync(paymentsCreateBookingPayment(
      this,
      request,
      options,
    ));
  }
}
