/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createOrderOrdersPost } from "../../funcs/createOrderOrdersPost.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CoffeeOrder$inboundSchema,
};

export const tool$createOrderOrdersPost: ToolDefinition<typeof args> = {
  name: "create-order-orders-post",
  description: `Create Order

Create a new coffee order.
Validates that the coffee type exists.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await createOrderOrdersPost(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
