/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createCoffeeTypeCoffeeTypesPost } from "../../funcs/createCoffeeTypeCoffeeTypesPost.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CoffeeType$inboundSchema,
};

export const tool$createCoffeeTypeCoffeeTypesPost: ToolDefinition<typeof args> =
  {
    name: "create-coffee-type-coffee-types-post",
    description: `Create Coffee Type

Create a new coffee type.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await createCoffeeTypeCoffeeTypesPost(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
