/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getOrderOrdersOrderIdGet } from "../../funcs/getOrderOrdersOrderIdGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetOrderOrdersOrderIdGetRequest$inboundSchema,
};

export const tool$getOrderOrdersOrderIdGet: ToolDefinition<typeof args> = {
  name: "get-order-orders-order-id-get",
  description: `Get Order

Retrieve a specific coffee order by its ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getOrderOrdersOrderIdGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
