/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateOrderOrdersOrderIdPut } from "../../funcs/updateOrderOrdersOrderIdPut.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateOrderOrdersOrderIdPutRequest$inboundSchema,
};

export const tool$updateOrderOrdersOrderIdPut: ToolDefinition<typeof args> = {
  name: "update-order-orders-order-id-put",
  description: `Update Order

Update an existing coffee order.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await updateOrderOrdersOrderIdPut(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
