/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesSetFeatureFlags } from "../../funcs/workspacesSetFeatureFlags.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.WorkspaceFeatureFlagRequest$inboundSchema,
};

export const tool$workspacesSetFeatureFlags: ToolDefinition<typeof args> = {
  name: "workspaces_set-feature-flags",
  description: `Set workspace feature flags`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspacesSetFeatureFlags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
