// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type BerryListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (b *BerryListRequest) GetLimit() *int64 {
	if b == nil {
		return nil
	}
	return b.Limit
}

func (b *BerryListRequest) GetOffset() *int64 {
	if b == nil {
		return nil
	}
	return b.Offset
}

type BerryListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (b *BerryListResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BerryListResponse) GetRes() *string {
	if b == nil {
		return nil
	}
	return b.Res
}
