// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type ContestEffectListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (c *ContestEffectListRequest) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *ContestEffectListRequest) GetOffset() *int64 {
	if c == nil {
		return nil
	}
	return c.Offset
}

type ContestEffectListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (c *ContestEffectListResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ContestEffectListResponse) GetRes() *string {
	if c == nil {
		return nil
	}
	return c.Res
}
