// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type EggGroupListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (e *EggGroupListRequest) GetLimit() *int64 {
	if e == nil {
		return nil
	}
	return e.Limit
}

func (e *EggGroupListRequest) GetOffset() *int64 {
	if e == nil {
		return nil
	}
	return e.Offset
}

type EggGroupListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (e *EggGroupListResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EggGroupListResponse) GetRes() *string {
	if e == nil {
		return nil
	}
	return e.Res
}
