// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type GenderReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GenderReadRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GenderReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (g *GenderReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenderReadResponse) GetRes() *string {
	if g == nil {
		return nil
	}
	return g.Res
}
