// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type GrowthRateReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GrowthRateReadRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GrowthRateReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (g *GrowthRateReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GrowthRateReadResponse) GetRes() *string {
	if g == nil {
		return nil
	}
	return g.Res
}
