// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type ItemFlingEffectListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (i *ItemFlingEffectListRequest) GetLimit() *int64 {
	if i == nil {
		return nil
	}
	return i.Limit
}

func (i *ItemFlingEffectListRequest) GetOffset() *int64 {
	if i == nil {
		return nil
	}
	return i.Offset
}

type ItemFlingEffectListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (i *ItemFlingEffectListResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *ItemFlingEffectListResponse) GetRes() *string {
	if i == nil {
		return nil
	}
	return i.Res
}
