// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type LanguageReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (l *LanguageReadRequest) GetID() int64 {
	if l == nil {
		return 0
	}
	return l.ID
}

type LanguageReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (l *LanguageReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LanguageReadResponse) GetRes() *string {
	if l == nil {
		return nil
	}
	return l.Res
}
