// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type MoveReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (m *MoveReadRequest) GetID() int64 {
	if m == nil {
		return 0
	}
	return m.ID
}

type MoveReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (m *MoveReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MoveReadResponse) GetRes() *string {
	if m == nil {
		return nil
	}
	return m.Res
}
