// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type MoveTargetListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (m *MoveTargetListRequest) GetLimit() *int64 {
	if m == nil {
		return nil
	}
	return m.Limit
}

func (m *MoveTargetListRequest) GetOffset() *int64 {
	if m == nil {
		return nil
	}
	return m.Offset
}

type MoveTargetListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (m *MoveTargetListResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MoveTargetListResponse) GetRes() *string {
	if m == nil {
		return nil
	}
	return m.Res
}
