// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type NatureListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (n *NatureListRequest) GetLimit() *int64 {
	if n == nil {
		return nil
	}
	return n.Limit
}

func (n *NatureListRequest) GetOffset() *int64 {
	if n == nil {
		return nil
	}
	return n.Offset
}

type NatureListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (n *NatureListResponse) GetHTTPMeta() components.HTTPMetadata {
	if n == nil {
		return components.HTTPMetadata{}
	}
	return n.HTTPMeta
}

func (n *NatureListResponse) GetRes() *string {
	if n == nil {
		return nil
	}
	return n.Res
}
