// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type PokeathlonStatListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (p *PokeathlonStatListRequest) GetLimit() *int64 {
	if p == nil {
		return nil
	}
	return p.Limit
}

func (p *PokeathlonStatListRequest) GetOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.Offset
}

type PokeathlonStatListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (p *PokeathlonStatListResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PokeathlonStatListResponse) GetRes() *string {
	if p == nil {
		return nil
	}
	return p.Res
}
