// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type PokedexReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (p *PokedexReadRequest) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

type PokedexReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (p *PokedexReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PokedexReadResponse) GetRes() *string {
	if p == nil {
		return nil
	}
	return p.Res
}
