// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type RegionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (r *RegionListRequest) GetLimit() *int64 {
	if r == nil {
		return nil
	}
	return r.Limit
}

func (r *RegionListRequest) GetOffset() *int64 {
	if r == nil {
		return nil
	}
	return r.Offset
}

type RegionListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (r *RegionListResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RegionListResponse) GetRes() *string {
	if r == nil {
		return nil
	}
	return r.Res
}
