// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type SuperContestEffectReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SuperContestEffectReadRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

type SuperContestEffectReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (s *SuperContestEffectReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SuperContestEffectReadResponse) GetRes() *string {
	if s == nil {
		return nil
	}
	return s.Res
}
