// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type TypeReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (t *TypeReadRequest) GetID() int64 {
	if t == nil {
		return 0
	}
	return t.ID
}

type TypeReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (t *TypeReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TypeReadResponse) GetRes() *string {
	if t == nil {
		return nil
	}
	return t.Res
}
