// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pokeapi/sdk/models/components"
)

type VersionGroupReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (v *VersionGroupReadRequest) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

type VersionGroupReadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default response
	Res *string
}

func (v *VersionGroupReadResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VersionGroupReadResponse) GetRes() *string {
	if v == nil {
		return nil
	}
	return v.Res
}
