/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A response message
 */
export type ResponseMessageErrorData = {
  /**
   * The response message
   */
  message: string;
};

/**
 * A response message
 */
export class ResponseMessageError extends Error {
  /** The original data that was passed to this error instance. */
  data$: ResponseMessageErrorData;

  constructor(err: ResponseMessageErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "ResponseMessageError";
  }
}

/** @internal */
export const ResponseMessageError$inboundSchema: z.ZodType<
  ResponseMessageError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new ResponseMessageError(v);
  });

/** @internal */
export type ResponseMessageError$Outbound = {
  message: string;
};

/** @internal */
export const ResponseMessageError$outboundSchema: z.ZodType<
  ResponseMessageError$Outbound,
  z.ZodTypeDef,
  ResponseMessageError
> = z.instanceof(ResponseMessageError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseMessageError$ {
  /** @deprecated use `ResponseMessageError$inboundSchema` instead. */
  export const inboundSchema = ResponseMessageError$inboundSchema;
  /** @deprecated use `ResponseMessageError$outboundSchema` instead. */
  export const outboundSchema = ResponseMessageError$outboundSchema;
  /** @deprecated use `ResponseMessageError$Outbound` instead. */
  export type Outbound = ResponseMessageError$Outbound;
}
