/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BookingPaymentSourceBankAccount,
  BookingPaymentSourceBankAccount$inboundSchema,
} from "./bookingpaymentsourcebankaccount.js";
import {
  BookingPaymentSourceCardOutput,
  BookingPaymentSourceCardOutput$inboundSchema,
} from "./bookingpaymentsourcecardoutput.js";

export const Currency = {
  Bam: "bam",
  Bgn: "bgn",
  Chf: "chf",
  Eur: "eur",
  Gbp: "gbp",
  Nok: "nok",
  Sek: "sek",
  Try: "try",
} as const;
export type Currency = ClosedEnum<typeof Currency>;

export type Links = {
  booking?: string | undefined;
};

export type Source =
  | BookingPaymentSourceCardOutput
  | BookingPaymentSourceBankAccount;

export const Status = {
  Pending: "pending",
  Succeeded: "succeeded",
  Failed: "failed",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type BookingPayment = {
  amount: number;
  currency: Currency;
  id?: string | undefined;
  links?: Links | undefined;
  source: BookingPaymentSourceCardOutput | BookingPaymentSourceBankAccount;
  status?: Status | undefined;
};

/** @internal */
export const Currency$inboundSchema: z.ZodNativeEnum<typeof Currency> = z
  .nativeEnum(Currency);

/** @internal */
export const Links$inboundSchema: z.ZodType<Links, z.ZodTypeDef, unknown> = z
  .object({
    booking: z.string().optional(),
  });

export function linksFromJSON(
  jsonString: string,
): SafeParseResult<Links, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Links$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Links' from JSON`,
  );
}

/** @internal */
export const Source$inboundSchema: z.ZodType<Source, z.ZodTypeDef, unknown> = z
  .union([
    BookingPaymentSourceCardOutput$inboundSchema,
    BookingPaymentSourceBankAccount$inboundSchema,
  ]);

export function sourceFromJSON(
  jsonString: string,
): SafeParseResult<Source, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Source$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Source' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const BookingPayment$inboundSchema: z.ZodType<
  BookingPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number(),
  currency: Currency$inboundSchema,
  id: z.string().optional(),
  links: z.lazy(() => Links$inboundSchema).optional(),
  source: z.union([
    BookingPaymentSourceCardOutput$inboundSchema,
    BookingPaymentSourceBankAccount$inboundSchema,
  ]),
  status: Status$inboundSchema.optional(),
});

export function bookingPaymentFromJSON(
  jsonString: string,
): SafeParseResult<BookingPayment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BookingPayment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BookingPayment' from JSON`,
  );
}
