/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TripResourceLinks = {
  destination?: string | undefined;
  origin?: string | undefined;
  self?: string | undefined;
};

export type TripResource = {
  arrivalTime?: Date | undefined;
  bicyclesAllowed?: boolean | undefined;
  departureTime?: Date | undefined;
  /**
   * The destination station id.
   */
  destination?: string | undefined;
  dogsAllowed?: boolean | undefined;
  id?: string | undefined;
  links?: TripResourceLinks | undefined;
  operator?: string | undefined;
  /**
   * The origin station id.
   */
  origin?: string | undefined;
  price?: number | undefined;
};

/** @internal */
export const TripResourceLinks$inboundSchema: z.ZodType<
  TripResourceLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  destination: z.string().optional(),
  origin: z.string().optional(),
  self: z.string().optional(),
});

export function tripResourceLinksFromJSON(
  jsonString: string,
): SafeParseResult<TripResourceLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TripResourceLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TripResourceLinks' from JSON`,
  );
}

/** @internal */
export const TripResource$inboundSchema: z.ZodType<
  TripResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  arrival_time: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  bicycles_allowed: z.boolean().optional(),
  departure_time: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  destination: z.string().optional(),
  dogs_allowed: z.boolean().optional(),
  id: z.string().optional(),
  links: z.lazy(() => TripResourceLinks$inboundSchema).optional(),
  operator: z.string().optional(),
  origin: z.string().optional(),
  price: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "arrival_time": "arrivalTime",
    "bicycles_allowed": "bicyclesAllowed",
    "departure_time": "departureTime",
    "dogs_allowed": "dogsAllowed",
  });
});

export function tripResourceFromJSON(
  jsonString: string,
): SafeParseResult<TripResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TripResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TripResource' from JSON`,
  );
}
