// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CoffeeOrder *components.CoffeeOrder
}

func (o *CreateOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateOrderResponse) GetCoffeeOrder() *components.CoffeeOrder {
	if o == nil {
		return nil
	}
	return o.CoffeeOrder
}
