// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetCoffeeTypesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseGetCoffeeTypesCoffeeTypesGet []components.CoffeeType
}

func (o *GetCoffeeTypesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCoffeeTypesResponse) GetResponseGetCoffeeTypesCoffeeTypesGet() []components.CoffeeType {
	if o == nil {
		return nil
	}
	return o.ResponseGetCoffeeTypesCoffeeTypesGet
}
