/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bookingsCreateBooking } from "../funcs/bookingsCreateBooking.js";
import { bookingsDeleteBooking } from "../funcs/bookingsDeleteBooking.js";
import { bookingsGetBooking } from "../funcs/bookingsGetBooking.js";
import { bookingsGetBookings } from "../funcs/bookingsGetBookings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Bookings extends ClientSDK {
  async createBooking(
    request: operations.CreateBookingRequestBody,
    options?: RequestOptions,
  ): Promise<shared.BookingResource> {
    return unwrapAsync(bookingsCreateBooking(
      this,
      request,
      options,
    ));
  }

  async deleteBooking(
    request: operations.DeleteBookingRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(bookingsDeleteBooking(
      this,
      request,
      options,
    ));
  }

  async getBooking(
    request: operations.GetBookingRequest,
    options?: RequestOptions,
  ): Promise<shared.BookingResource> {
    return unwrapAsync(bookingsGetBooking(
      this,
      request,
      options,
    ));
  }

  async getBookings(
    request?: operations.GetBookingsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetBookingsResponseBody> {
    return unwrapAsync(bookingsGetBookings(
      this,
      request,
      options,
    ));
  }
}
