/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthGetHealth } from "../funcs/healthGetHealth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Health extends ClientSDK {
  async getHealth(
    options?: RequestOptions,
  ): Promise<operations.GetHealthResponseBody> {
    return unwrapAsync(healthGetHealth(
      this,
      options,
    ));
  }
}
