/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tripsGetTrips } from "../funcs/tripsGetTrips.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Trips extends ClientSDK {
  async getTrips(
    request: operations.GetTripsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTripsResponseBody> {
    return unwrapAsync(tripsGetTrips(
      this,
      request,
      options,
    ));
  }
}
